-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 16:50:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema netfloux
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema netfloux
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netfloux` DEFAULT CHARACTER SET utf8 ;
USE `netfloux` ;

-- -----------------------------------------------------
-- Table `netfloux`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netfloux`.`categories` ;

CREATE TABLE IF NOT EXISTS `netfloux`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netfloux`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netfloux`.`movies` ;

CREATE TABLE IF NOT EXISTS `netfloux`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `duration` TIME NOT NULL,
  `watched` TINYINT NOT NULL,
  `minimum_age` INT NOT NULL,
  `streaming_site` VARCHAR(15) NOT NULL,
  `release_date` DATE NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `trailer_link` VARCHAR(50) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movies_categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_movies_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `netfloux`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflouxcommentaries`.`commentaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netfloux`.`commentaries` ;

CREATE TABLE IF NOT EXISTS `netfloux`.`commentaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentar` VARCHAR(255) NOT NULL,
  `rate` SMALLINT(1) NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaries_movies1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaries_movies1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `netfloux`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
